# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      # Download and cache dependencies
      - run:
          name: mkdir report test
          command: |
            cd api
            mkdir test-reports
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "api/requirements.txt"}}
      - run:
          name: install dependencies
          command: |
            virtualenv env
            . env/bin/activate
            cd api
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "api/requirements.txt"}}
          paths:
            - 'env'

      # run tests!
      - run:
          name: run tests
          command: |
            virtualenv env
            . env/bin/activate
            cd api
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
          