#!/bin/bash

protected_branches=('master')
protected_branches2=${protected_branches[@]##$current_branch}
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ ${#protected_branches[*]} != ${#protected_branches2[*]} ]
then
    tput setaf 1
    echo "Trying to push to master, shame on you!"
    tput sgr0
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi

